version: "3.9"

services:
    app:
        env_file:
            - .env
        build:
            context: .
            args:
                - DEV=true
        ports:
            - "8000:8000"
        volumes:
            - ./app:/app
        command: >
            sh -c "python manage.py wait_for_db &&
                   python manage.py migrate &&
                   python manage.py runserver 0.0.0.0:8000"

        depends_on: # db service must be up before app service
            - db
        secrets:
            - db-password

    db:
        image: postgres:13.3-alpine
        volumes:
            - db-data:/var/lib/postgresql/data/
        environment: # set database configuration when first starting the container
            - POSTGRES_DB=ai-yearbook-db
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
        secrets:
            - db-password

volumes:
    db-data: # handled automatically by docker-compose (store in the default location)

secrets:
    db-password:
        file: ./db_password.txt
