version: "3.9"

services:
    app:
        env_file:
            - .env
        build:
            context: .
            args:
                - DEV=true
        ports:
            - "8000:8000"
        volumes:
            - ./app:/app
        command: >
            sh -c "python manage.py wait_for_db &&
                    python manage.py migrate &&
                    python manage.py runserver 127.0.0.1:8000"
    #    environment:
    #        - DJANGO_SECRET_KEY=jango-insecure--#6okigcc *.crnjw=293trolfev^dg(_j_vrsk7t5bj+q/usr/share/zsh/5.9/functions*b)s7g@

    #         - DB_HOST=db
    #         - DB_NAME=devdb
    #         - DB_USER=devuser
    #         - DB_PASSWORD=changeme
    #     depends_on:
    #         - db

    # db:
    #     image: postgres:13.3-alpine
    #     volumes:
    #         - postgres_data:/var/lib/postgresql/data/
    #     environment:
    #         - POSTGRES_DB=devdb
    #         - POSTGRES_USER=devuser
    #         - POSTGRES_PASSWORD=changeme
