# configurations for github action
---
name: Checks

on:
    push:
        branches: ["main"]

jobs:
    test-lint:
        name: Test and Lint
        runs-on: ubuntu-20.04
        steps:
            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USER }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Checkout
              uses: actions/checkout@v2
            - name: Generate Environment Variables File
                run: |
                  echo "DB_NAME=$DB_NAME" >> .env
                  echo "DB_USER=$DB_USER" >> .env
                  echo "DB_PASSWORD=$DB_PASSWORD" >> .env
                  echo "DB_HOST=$DB_HOST" >> .env
                  echo "DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY" >> .env
                env:
                  DB_NAME: ${{ secrets.DB_NAME }}
                  DB_USER: ${{ secrets.DB_USER }}
                  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
                  DB_HOST: ${{ secrets.DB_HOST }}
                  DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
            - name: Test
              run: docker-compose run --rm app sh -c "python manage.py test"
            - name: Lint
              run: docker-compose run --rm app sh -c "flake8"
